model: log/log_bio_aoa/model.pdparams
infos_path: log/log_bio_aoa/infos_aoanet.pkl

input_json: data/customtalk_bio.json
input_label_h5: data/customtalk_label_bio.h5
input_fc_dir: data/biobu_fc
input_att_dir: data/biobu_att
input_box_dir: data/biobu_box


dump_images: 0
dump_json: 1
num_images: -1
language_eval: 1
beam_size: 3
batch_size: 1
split: test