id: aoanet
start_from: log/log_bio_aoa
caption_model: aoa
refine: 1
refine_aoa: 1
use_ff: 0
num_heads: 8
mean_feats: 1
ctx_drop: 1
dropout_aoa: 0.3
label_smoothing: 0.2
input_json: data/customtalk_bio.json
input_label_h5: data/customtalk_label_bio.h5
input_fc_dir: data/biobu_fc
input_att_dir: data/biobu_att
input_box_dir: data/biobu_box

seq_per_img: 1
batch_size: 12
beam_size: 1
learning_rate: 0.00002
num_layers: 2
input_encoding_size: 1024
rnn_size: 1024
fc_feat_size: 2048
att_feat_size: 2048
learning_rate_decay_start: -1
scheduled_sampling_start: 0
checkpoint_path: log/log_bio_aoa

save_checkpoint_every: 7000
language_eval: 1
val_images_use: -1
max_epochs: 500
scheduled_sampling_increase_every: 5
scheduled_sampling_max_prob: 0.5
learning_rate_decay_every: 3
split: val